In [46]:
import pandas as pd

* Series (1-dimensional):

In [47]:
Car_make = pd.Series(["BMW", "Toyota", "Honda", "Tesla", "Mercedes"])

In [48]:
Country = pd.Series(["Germany", "Japan", "Japan", "USA", "Germany"])

* DataFrames (2-dimensional):

In [49]:
car_data = pd.DataFrame({
    "Make" : Car_make,
    "Country" : Country
})

car_data

       Make  Country
0       BMW  Germany
1    Toyota    Japan
2     Honda    Japan
3     Tesla      USA
4  Mercedes  Germany

* Importing data from .csv files:

In [50]:
car_sales = pd.read_csv("car-sales.csv")

In [51]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

* Exporting a DataFrame:

In [52]:
#Exporting as .csv file:
Export_to_csv = car_sales.to_csv("Cars_data.csv")

In [53]:
#Exporting as .xlsx file:
Export_to_Xlsx = car_sales.to_excel("Cars_data.xlsx")